export const RULES = "2.3";
export const LEGACY_EXPANDED_RULES = "2.2";
export const LEGACY_OPENING_RULES = "2.1";
export const hasOpening = (rules) =>
  [RULES, LEGACY_EXPANDED_RULES, LEGACY_OPENING_RULES].includes(rules);
export const LEGACY_FINITE_RULES = "2.0";
export const hasFiniteRituals = (rules) =>
  [
    RULES,
    LEGACY_EXPANDED_RULES,
    LEGACY_OPENING_RULES,
    LEGACY_FINITE_RULES,
  ].includes(rules);
export const LEGACY_RULES = "1.0";
export const RITUAL_LIMIT = 4;
export const CONTENT_VERSION = "pep1-2026.1";
export const LEGACY_CONTENT = "general-1.0";
export const validCourse = (course) =>
  typeof course === "string" && /^(all|s[12](?:-u[1-6])?)$/.test(course);
export const CARDS = [
  {
    id: "sprout",
    element: "nature",
    name: "芽芽精灵",
    en: "Sprout",
    cost: 1,
    atk: 1,
    hp: 3,
    art: 6,
    theme: "leaf",
    text: "小小的种子，也能守住森林。",
  },
  {
    id: "rabbit",
    element: "arcane",
    name: "月光兔",
    en: "Moon Hare",
    cost: 1,
    atk: 2,
    hp: 1,
    art: 4,
    theme: "moon",
    keyword: "rush",
    text: "迅捷 · 登场即可攻击",
  },
  {
    id: "fox",
    element: "arcane",
    name: "寻路狐狸",
    en: "Trail Fox",
    cost: 2,
    atk: 2,
    hp: 2,
    art: 0,
    theme: "ember",
    keyword: "draw",
    text: "登场 · 抽1张牌",
  },
  {
    id: "sprite",
    element: "nature",
    name: "青苔幼灵",
    en: "Mossling",
    cost: 2,
    atk: 1,
    hp: 3,
    art: 7,
    theme: "leaf",
    keyword: "grow",
    text: "成长 · 回合开始时攻击+1",
  },
  {
    id: "turtle",
    element: "nature",
    name: "苔石守卫",
    en: "Moss Guard",
    cost: 3,
    atk: 1,
    hp: 5,
    art: 2,
    theme: "leaf",
    keyword: "guard",
    text: "守卫 · 敌人须优先攻击它",
  },
  {
    id: "owl",
    element: "arcane",
    name: "星辉学者",
    en: "Star Owl",
    cost: 3,
    atk: 3,
    hp: 3,
    art: 1,
    theme: "moon",
    keyword: "armor",
    text: "登场 · 你的英雄获得2护甲",
  },
  {
    id: "stag",
    element: "nature",
    name: "森之使者",
    en: "Grove Deer",
    cost: 4,
    atk: 3,
    hp: 5,
    art: 5,
    theme: "leaf",
    keyword: "heal",
    text: "登场 · 为你的英雄恢复3生命",
  },
  {
    id: "dragon",
    element: "fire",
    name: "烛火幼龙",
    en: "Ember Drake",
    cost: 5,
    atk: 5,
    hp: 4,
    art: 3,
    theme: "ember",
    keyword: "rush",
    text: "迅捷 · 登场即可攻击",
  },
  {
    id: "golem",
    element: "arcane",
    name: "远古岩灵",
    en: "Ancient Golem",
    cost: 5,
    atk: 4,
    hp: 7,
    art: 8,
    theme: "moon",
    keyword: "guard",
    text: "守卫 · 敌人须优先攻击它",
  },
  {
    id: "spark",
    element: "fire",
    name: "星火术",
    en: "Spark",
    cost: 2,
    type: "spell",
    art: 9,
    theme: "ember",
    keyword: "damage",
    text: "对任意敌人造成3点伤害",
  },
  {
    id: "bloom",
    element: "water",
    name: "春生术",
    en: "Bloom",
    cost: 2,
    type: "spell",
    art: 10,
    theme: "leaf",
    keyword: "restore",
    text: "为你的英雄恢复5生命",
  },
  {
    id: "moon",
    element: "arcane",
    name: "月之启示",
    en: "Moonlight",
    cost: 3,
    type: "spell",
    art: 11,
    theme: "moon",
    keyword: "insight",
    text: "抽2张牌",
  },
  {
    id: "hedgehog",
    element: "nature",
    name: "刺果卫士",
    en: "Berry Hedgehog",
    cost: 1,
    atk: 1,
    hp: 2,
    art: 12,
    theme: "leaf",
    keyword: "guard",
    text: "守卫 · 敌人须优先攻击它",
  },
  {
    id: "otter",
    element: "water",
    name: "溪流海獭",
    en: "River Otter",
    cost: 2,
    atk: 2,
    hp: 2,
    art: 13,
    theme: "leaf",
    keyword: "barrier",
    text: "护盾 · 抵挡第一次伤害",
  },
  {
    id: "firefly",
    element: "arcane",
    name: "提灯萤",
    en: "Lantern Firefly",
    cost: 1,
    atk: 1,
    hp: 1,
    art: 14,
    theme: "moon",
    keyword: "draw",
    text: "登场 · 抽1张牌",
  },
  {
    id: "wolf",
    element: "fire",
    name: "赤焰狼",
    en: "Ember Wolf",
    cost: 3,
    atk: 4,
    hp: 2,
    art: 15,
    theme: "ember",
    keyword: "rush",
    text: "迅捷 · 登场即可攻击",
  },
  {
    id: "crane",
    element: "water",
    name: "云羽鹤",
    en: "Cloud Crane",
    cost: 3,
    atk: 2,
    hp: 4,
    art: 16,
    theme: "moon",
    keyword: "heal",
    text: "登场 · 为你的英雄恢复3生命",
  },
  {
    id: "boar",
    element: "fire",
    name: "燧石野猪",
    en: "Flint Boar",
    cost: 4,
    atk: 3,
    hp: 3,
    art: 17,
    theme: "ember",
    keyword: "rally",
    text: "鼓舞 · 登场让其他友方伙伴攻击+1",
  },
  {
    id: "bear",
    element: "nature",
    name: "古树熊",
    en: "Oak Bear",
    cost: 4,
    atk: 3,
    hp: 6,
    art: 18,
    theme: "leaf",
    keyword: "guard",
    text: "守卫 · 敌人须优先攻击它",
  },
  {
    id: "unicorn",
    element: "arcane",
    name: "月泉独角兽",
    en: "Moonwell Unicorn",
    cost: 4,
    atk: 2,
    hp: 5,
    art: 19,
    theme: "moon",
    keyword: "grow",
    text: "成长 · 回合开始时攻击+1",
  },
  {
    id: "phoenix",
    element: "fire",
    name: "晨火凰",
    en: "Dawn Phoenix",
    cost: 6,
    atk: 6,
    hp: 5,
    art: 20,
    theme: "ember",
    keyword: "rush",
    text: "迅捷 · 登场即可攻击",
  },
  {
    id: "frost",
    element: "water",
    name: "霜星术",
    en: "Frost Star",
    cost: 4,
    type: "spell",
    art: 21,
    theme: "moon",
    keyword: "damage",
    amount: 5,
    text: "对任意敌人造成5点伤害",
  },
  {
    id: "dew",
    element: "water",
    name: "晨露术",
    en: "Morning Dew",
    cost: 1,
    type: "spell",
    art: 22,
    theme: "leaf",
    keyword: "restore",
    amount: 3,
    text: "为你的英雄恢复3生命",
  },
  {
    id: "lantern",
    element: "arcane",
    name: "引路灯",
    en: "Guiding Light",
    cost: 1,
    type: "spell",
    art: 23,
    theme: "moon",
    keyword: "insight",
    amount: 1,
    text: "抽1张牌",
  },
  {
    id: "acorn_squirrel",
    name: "橡果松鼠",
    en: "Acorn Squirrel",
    cost: 1,
    atk: 1,
    hp: 2,
    element: "nature",
    theme: "leaf",
    art: 24,
    artPath: "/assets/cards-v4/acorn_squirrel.webp",
    introducedRules: "2.3",
    keyword: "deathArmor",
    amount: 2,
    text: "退场 · 生命降至0时，你的英雄获得2护甲；回手不触发",
  },
  {
    id: "mushroom_medic",
    name: "蘑菇医师",
    en: "Mushroom Medic",
    cost: 2,
    atk: 1,
    hp: 3,
    element: "nature",
    theme: "leaf",
    art: 25,
    artPath: "/assets/cards-v4/mushroom_medic.webp",
    introducedRules: "2.3",
    keyword: "mend",
    amount: 3,
    target: "friendly-wounded-unit",
    text: "登场 · 为另一个友方伙伴恢复3生命，不超过最大生命",
  },
  {
    id: "reed_frog",
    name: "芦苇蛙",
    en: "Reed Frog",
    cost: 2,
    atk: 2,
    hp: 2,
    element: "water",
    theme: "leaf",
    art: 26,
    artPath: "/assets/cards-v4/reed_frog.webp",
    introducedRules: "2.3",
    keyword: "weaken",
    amount: 1,
    target: "enemy-unit",
    text: "登场 · 一个敌方伙伴攻击−1，最低0；持续至它离场",
  },
  {
    id: "glass_snail",
    name: "琉璃蜗牛",
    en: "Glass Snail",
    cost: 3,
    atk: 1,
    hp: 4,
    element: "water",
    theme: "moon",
    art: 27,
    artPath: "/assets/cards-v4/glass_snail.webp",
    introducedRules: "2.3",
    keyword: "grantShield",
    target: "friendly-unshielded-unit",
    text: "登场 · 使另一个没有护盾的友方伙伴获得护盾，抵挡下一次正伤害",
  },
  {
    id: "storm_kingfisher",
    name: "风羽翠鸟",
    en: "Wind Kingfisher",
    cost: 3,
    atk: 3,
    hp: 2,
    element: "arcane",
    theme: "moon",
    art: 28,
    artPath: "/assets/cards-v4/storm_kingfisher.webp",
    introducedRules: "2.3",
    keyword: "heroHitDraw",
    amount: 1,
    text: "命中 · 主动攻击敌方英雄并扣除生命后抽1张牌，每本人回合至多1次",
  },
  {
    id: "sun_badger",
    name: "晨光獾",
    en: "Dawn Badger",
    cost: 4,
    atk: 3,
    hp: 5,
    element: "fire",
    theme: "ember",
    art: 29,
    artPath: "/assets/cards-v4/sun_badger.webp",
    introducedRules: "2.3",
    keyword: "companyArmor",
    amount: 1,
    limit: 3,
    text: "登场 · 每有1个其他友方伙伴，你的英雄获得1护甲，最多3",
  },
  {
    id: "crystal_ram",
    name: "晶角羊",
    en: "Crystal Ram",
    cost: 4,
    atk: 4,
    hp: 4,
    element: "arcane",
    theme: "moon",
    art: 30,
    artPath: "/assets/cards-v4/crystal_ram.webp",
    introducedRules: "2.3",
    keyword: "unitCharge",
    amount: 1,
    text: "冲角 · 主动攻击敌方伙伴时，本次伤害+1；打英雄与还击不加成",
  },
  {
    id: "ember_salamander",
    name: "炉火蝾螈",
    en: "Hearth Salamander",
    cost: 5,
    atk: 3,
    hp: 5,
    element: "fire",
    theme: "ember",
    art: 31,
    artPath: "/assets/cards-v4/ember_salamander.webp",
    introducedRules: "2.3",
    keyword: "arrivalDamage",
    amount: 2,
    target: "enemy-unit",
    text: "登场 · 对一个敌方伙伴造成2伤害，不能指定英雄",
  },
  {
    id: "thorn_sweep",
    name: "荆棘扫掠",
    en: "Thorn Sweep",
    cost: 2,
    type: "spell",
    element: "nature",
    theme: "leaf",
    art: 32,
    artPath: "/assets/cards-v4/thorn_sweep.webp",
    introducedRules: "2.3",
    keyword: "sweep",
    amount: 1,
    target: "all-enemy-units",
    text: "同时对所有敌方伙伴各造成1伤害，不伤害英雄；无目标不可用",
  },
  {
    id: "mending_rain",
    name: "修复之雨",
    en: "Mending Rain",
    cost: 2,
    type: "spell",
    element: "water",
    theme: "leaf",
    art: 33,
    artPath: "/assets/cards-v4/mending_rain.webp",
    introducedRules: "2.3",
    keyword: "rain",
    amount: 2,
    target: "all-friendly-wounded-units",
    text: "为所有友方伙伴各恢复2生命，不超过最大生命；没有受伤伙伴不可用",
  },
  {
    id: "tidal_recall",
    name: "潮汐归途",
    en: "Tidal Recall",
    cost: 1,
    type: "spell",
    element: "water",
    theme: "moon",
    art: 34,
    artPath: "/assets/cards-v4/tidal_recall.webp",
    introducedRules: "2.3",
    keyword: "recall",
    target: "friendly-unit",
    text: "将1个友方伙伴送回手牌，恢复为基础卡；清除所有伤害、强化与状态",
  },
  {
    id: "sunseed_blessing",
    name: "阳种祝福",
    en: "Sunseed Blessing",
    cost: 2,
    type: "spell",
    element: "nature",
    theme: "leaf",
    art: 35,
    artPath: "/assets/cards-v4/sunseed_blessing.webp",
    introducedRules: "2.3",
    keyword: "blessing",
    amount: 2,
    target: "friendly-unit",
    text: "使1个友方伙伴最大生命+2，并立即恢复2生命；持续至它离场",
  },
];
export const CARD = Object.fromEntries(CARDS.map((c) => [c.id, c]));
// Old matches keep their original card catalog and rules when resumed.
export const isCardAvailable = (id, rules = RULES) =>
  Object.hasOwn(CARD, id) && (!CARD[id].introducedRules || rules === RULES);
// Only IDs cross the network. Combat values always come from the server's CARD.
export function validateCustomDeck(ids) {
  if (!Array.isArray(ids) || ids.length !== 20) return false;
  const copies = new Map();
  for (const id of ids) {
    if (typeof id !== "string" || !Object.hasOwn(CARD, id)) return false;
    copies.set(id, (copies.get(id) || 0) + 1);
    if (copies.get(id) > 3) return false;
  }
  return true;
}
export const DECKS = [
  {
    id: "grove",
    name: "森之守护",
    sub: "守卫保护 · 成长反击",
    theme: "leaf",
    ids: [
      "sprout",
      "sprout",
      "hedgehog",
      "hedgehog",
      "otter",
      "otter",
      "fox",
      "sprite",
      "sprite",
      "turtle",
      "crane",
      "bear",
      "bear",
      "stag",
      "golem",
      "spark",
      "spark",
      "dew",
      "bloom",
      "lantern",
    ],
  },
  {
    id: "ember",
    name: "星火突袭",
    sub: "迅捷进攻 · 把握致胜时机",
    theme: "ember",
    ids: [
      "rabbit",
      "rabbit",
      "sprout",
      "firefly",
      "fox",
      "fox",
      "otter",
      "wolf",
      "wolf",
      "owl",
      "crane",
      "boar",
      "boar",
      "dragon",
      "dragon",
      "phoenix",
      "spark",
      "spark",
      "dew",
      "lantern",
    ],
  },
  {
    id: "moon",
    name: "月影谋略",
    sub: "保持手牌 · 寻找最佳交换",
    theme: "moon",
    ids: [
      "firefly",
      "firefly",
      "hedgehog",
      "sprout",
      "fox",
      "fox",
      "sprite",
      "otter",
      "owl",
      "owl",
      "crane",
      "turtle",
      "unicorn",
      "unicorn",
      "golem",
      "spark",
      "frost",
      "dew",
      "moon",
      "lantern",
    ],
  },
];
// Easy computer games announce this fixed foundation deck before play.
// Deck selection is never adjusted in response to a hand, draw, or answer.
export const PRACTICE_DECK = Object.freeze({
  id: "foundation",
  name: "林间基础套牌",
  ids: Object.freeze([
    "sprout",
    "sprout",
    "sprout",
    "hedgehog",
    "firefly",
    "firefly",
    "fox",
    "fox",
    "fox",
    "turtle",
    "owl",
    "owl",
    "stag",
    "dew",
    "bloom",
    "lantern",
    "lantern",
    "lantern",
    "spark",
    "spark",
  ]),
});
export const OPPONENTS = [
  {
    id: "ember",
    name: "Ember",
    title: "烛火旅人",
    desc: "喜欢快节奏进攻，善于把伤害留给致胜的一击。",
    style: "aggro",
    art: 3,
    deck: "ember",
  },
  {
    id: "moss",
    name: "Moss",
    title: "森林守望者",
    desc: "重视随从交换与守卫，会先处理危险的敌人。",
    style: "control",
    art: 2,
    deck: "grove",
  },
  {
    id: "luna",
    name: "Luna",
    title: "月光研习者",
    desc: "珍惜手牌和成长随从，擅长为后续回合铺路。",
    style: "value",
    art: 1,
    deck: "moon",
  },
];
export const GRADES = [
  { n: 1, name: "萌芽森林", sub: "颜色 · 动物 · 生活短句" },
  { n: 2, name: "溪流小径", sub: "家庭朋友 · 天气 · 作息与星期" },
  { n: 3, name: "星光营地", sub: "校园家庭 · 正在做的事 · 活动计划" },
  { n: 4, name: "月影书院", sub: "交通问路 · 爱好频率 · 旅行意愿" },
  { n: 5, name: "远行山谷", sub: "人物购物 · 过去经历 · 日常建议" },
  { n: 6, name: "晨曦之巅", sub: "旅行文化 · 信息整合 · 语境理解" },
];
