import {CARDS,CARD,DECKS,validateCustomDeck} from '../cards.mjs';
import {cardGuide} from '../card-guide.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function cardArtUrl(id){const c=CARD[id];return c.artPath || (c.art>=6?`/assets/cards/${id}.webp`:'/assets/creatures.webp');}
export function artThumb(id){const c=CARD[id];return `<span class="library-art" style="background-image:url('${cardArtUrl(id)}');${c.art<6?`background-size:300% 200%;background-position:${c.art%3*50}% ${Math.floor(c.art/3)*100}%`:''}" aria-hidden="true"></span>`;}
export function replaceDeckCard(ids,index,replacement){if(!Number.isInteger(index)||index<0||index>=ids.length||!Object.hasOwn(CARD,replacement))return null;const next=[...ids];next[index]=replacement;return validateCustomDeck(next)?next:null;}
export class CardLibrary {
 constructor({preferences,onSave,onChange=()=>{},onNotice=()=>{},onClose=()=>{}}){Object.assign(this,{preferences,onSave,onChange,onNotice,onClose});this.tab='cards';this.selected='sprout';this.draft=[];this.busy=false;this.replaceIndex=null;}
 open(){const p=this.preferences();this.draft=[...(p.deckId==='custom'&&validateCustomDeck(p.customDeck)?p.customDeck:(DECKS.find(d=>d.id===p.deckId)||DECKS[0]).ids)];this.tab='deck';this.selected=this.draft[0];this.replaceIndex=null;}
 counts(){return Object.fromEntries(CARDS.map(c=>[c.id,this.draft.filter(id=>id===c.id).length]));}
 html(){const count=this.counts(),c=CARD[this.selected],g=cardGuide(c.id);return `<section class="dialog card-library" role="dialog" aria-modal="true" aria-labelledby="library-title"><header class="library-heading"><div><p class="eyebrow">THE FIELD GUIDE</p><h2 id="library-title">卡牌与组牌</h2></div><button data-action="library-close" ${this.busy?'disabled':''}>返回营地</button></header><p class="subtle">${CARDS.length}张基础战斗卡全部免费。人物和卡牌外观不增加战斗数值。</p><div class="library-tabs"><button data-action="library-tab" data-value="deck" aria-pressed="${this.tab==='deck'}">配好20张</button><button data-action="library-tab" data-value="cards" aria-pressed="${this.tab==='cards'}">看懂卡牌</button></div>${this.tab==='deck'?`<div class="deck-recommendations">${DECKS.map(d=>`<article><h3>${esc(d.name)}</h3><p>${esc(d.sub)}</p><button data-action="library-equip-preset" data-value="${d.id}" ${this.busy?'disabled':''}>一键使用</button></article>`).join('')}</div><details class="deck-edit" open><summary>微调我的20张 · 每种最多3张</summary><p class="deck-swap-hint" role="status">${this.replaceIndex===null?'先点下方一张旧卡，再从图鉴选一张换进来':`已选「${esc(CARD[this.draft[this.replaceIndex]].name)}」：点图鉴里的新卡完成替换`}</p><div class="deck-slots" role="group" aria-label="当前20张套牌">${this.draft.map((id,i)=>`<button data-action="library-slot" data-value="${i}" aria-pressed="${this.replaceIndex===i}" ${this.busy?'disabled':''}>${artThumb(id)}<span>${esc(CARD[id].name)}</span><small>${CARD[id].cost}能量</small></button>`).join('')}</div></details>`:''}<div class="library-layout"><div class="library-grid" aria-label="全部免费基础卡">${[...CARDS].sort((a,b)=>a.cost-b.cost).map(x=>`<button class="library-card ${x.id===c.id?'chosen':''}" data-action="library-card" data-value="${x.id}" ${this.busy?'disabled':''} aria-label="${esc(x.name)}，${x.cost}能量${this.tab==='deck'?`，已选${count[x.id]}张`:''}">${artThumb(x.id)}<b class="library-cost">${x.cost}</b><strong>${esc(x.name)}</strong><span>${this.tab==='deck'?`已选 ${count[x.id]}/3`:x.type==='spell'?'法术':`${x.atk}攻击 · ${x.hp}生命`}</span></button>`).join('')}</div><aside class="library-detail"><p class="eyebrow">${esc(g.element)} · ${esc(g.keyword)}</p><h3>${esc(c.name)}</h3><p class="card-facts">${g.cost} 能量${g.type==='伙伴'?` · ${g.atk} 攻击 · ${g.hp} 生命`:' · 法术'}</p><p class="card-effect">${esc(c.text)}</p><p>${esc(g.target)}</p><p>${esc(g.timing)}</p><p>${esc(g.rule)}</p><details class="card-info-tip"><summary>${g.exchange?'攻击前看看':'使用小提示'}</summary>${g.exchange?`<p>${esc(g.exchange)}</p>`:''}<p>${esc(g.tip)}</p></details><h4>试试看</h4><p>${esc(g.example)}</p></aside></div>${this.tab==='deck'?`<footer class="deck-footer"><p>当前${this.draft.length}/20张 · 每种最多3张</p><div><button data-action="library-cancel-swap" ${this.replaceIndex===null||this.busy?'disabled':''}>取消替换</button><button class="primary" data-action="library-save" ${!validateCustomDeck(this.draft)||this.busy?'disabled':''}>${this.busy?'正在保存…':'保存并使用'}</button></div></footer>`:''}</section>`;}
 async save(ids){if(this.busy||!validateCustomDeck(ids))return;this.busy=true;this.onChange();try{const ok=await this.onSave([...ids]);if(ok){this.onNotice('20张套牌已保存，下一局就用它');this.onClose();}else this.onNotice('套牌尚未保存，请重试保存');}finally{this.busy=false;this.onChange();}}
 async click(action,value){
  if(action==='library-close'){if(!this.busy)this.onClose();return;}if(this.busy)return;
  if(action==='library-tab'&&['cards','deck'].includes(value)){this.tab=value;this.replaceIndex=null;}
  if(action==='library-slot'&&Number.isInteger(Number(value))&&Number(value)>=0&&Number(value)<this.draft.length){this.replaceIndex=Number(value);this.selected=this.draft[this.replaceIndex];}
  if(action==='library-card'&&Object.hasOwn(CARD,value)){this.selected=value;if(this.tab==='deck'&&this.replaceIndex!==null){const next=replaceDeckCard(this.draft,this.replaceIndex,value);if(next){this.draft=next;this.replaceIndex=null;this.onNotice('已换好一张，保存后下局使用');}else this.onNotice('每种牌最多3张，请选另一张');}}
  if(action==='library-cancel-swap')this.replaceIndex=null;
  if(action==='library-equip-preset'){const d=DECKS.find(d=>d.id===value);if(d){this.draft=[...d.ids];await this.save(this.draft);}return;}
  if(action==='library-save'){await this.save(this.draft);return;}
  this.onChange();
 }
}
